### PR TITLE
Correctly parse heights from script-encoded int64 values

### LINKED ISSUE #35: Issue ingesting blocks with block_height as -1
After following installation instructions when starting zcashd with -reindex I get the following error:

```
INFO[2019-04-23T19:11:05-07:00] Listening to 0mq on 127.0.0.1:28332           app=zmqclient
INFO[2019-04-23T19:11:38-07:00] new block                                     app=zmqclient block_hash=382c4a332661c7ed0671f32a34d724619f086c61873bce7c99859dd9920aa605block_height=0 block_version=4 error="<nil>" sapling=false seqnum=0 tx_count=1
INFO[2019-04-23T19:11:38-07:00] new block                                     app=zmqclient block_hash=238d665a062b9007836a7d8f968ba2f3847af5f542733389a952cf9b86795502block_height=-1 block_version=4 error="<nil>" sapling=false seqnum=1 tx_count=1
ERROR[2019-04-23T19:11:38-07:00] new block                                     app=zmqclient block_hash=181ac2d6dc0ae73a82d7db472ac2879a7c24d8b12e5f73efc33a55549ea4f100 block_height=-1 block_version=4 error="storing compact block -1: UNIQUE constraint failed: blocks.block_height" sapling=false seqnum=2 tx_count=1
ERROR[2019-04-23T19:11:46-07:00] error on msg recv                             app=zmqclient error="interrupted system call"
```

In addition, viewing the sqlite database for the `blocks` table I see the following for `block_height` 0 and the `compact encoding` field:

```
 8,J3&aq*4$ala;|ْ
 
```

Running go 1.12.2 and zcashd v2.0.4 on Ubuntu 19.0.4.

### PR DESCRIPTION
**Pull request by str4d**
This enables the parser to correctly extract heights for blocks 1 through 16.

Closes #35.

### CODE REVIEW

File: parser/block.go [hunk 1]
```diff
@@ -62,21 +62,15 @@ func (b *block) GetHeight() int {
...
+	if heightNum < 0 {
 		return -1
 	}
 	// uint32 should last us a while (Nov 2018)
-	var blockHeight uint32
-	for i := heightLen - 1; i >= 0; i-- {
-		blockHeight <<= 8
-		blockHeight = blockHeight | uint32(heightBytes[i])
-	}
+	blockHeight := uint32(heightNum)
```
Comment (gtank) [inline parser/block.go]: Since the read API returns a uint64, we need to do range checking on this conversion somewhere.

File: parser/internal/bytestring/bytestring.go [hunk 2]
```diff
@@ -9,6 +9,11 @@ import (
 
 const MAX_COMPACT_SIZE uint64 = 0x02000000
 
+const OP_0 uint8 = 0x00
```
Comment (gtank) [inline parser/internal/bytestring/bytestring.go]: It would be better style to declare all of these in a block like:
```
const (
    OP_0 uint8 = 0x00
    ....
)```

Comment (gtank) [reply parser/internal/bytestring/bytestring.go]: Also, [idiomatically](https://golang.org/doc/effective_go.html#mixed-caps) these names should be camel case instead of capitals and underscores. They probably also don't need to be exported, so: `op0`, `op1Negate`, and so on. It may be an exception here if we're trying to match exact C++ code. I seem to have thought that previously, but really the above const _should_ have been called `maxCompactSize`.

File: parser/internal/bytestring/bytestring.go [hunk 3]
```diff
@@ -194,3 +199,42 @@ func (s *String) ReadUint64(out *uint64) bool {
...
+	firstByte := firstBytes[0]
+
+	var number uint64
+
+	if firstByte == OP_1NEGATE {
+		*num = -1
+		return true
+	} else if firstByte == OP_0 {
+		number = 0
+	} else if firstByte >= OP_1 && firstByte <= OP_16 {
```
Comment (gtank) [inline parser/internal/bytestring/bytestring.go]: It's not clear that this is correct. The C++ code seems to be directly comparing to the numbers 1 and 16, not these opcode values.

Comment (str4d) [reply parser/internal/bytestring/bytestring.go]: That's intentional. The referenced C++ code implements the serialization side; this function implements the parsing side. Parsing in `zcashd` would happen in the bowels of the script system.

Comment (str4d) [reply parser/internal/bytestring/bytestring.go]: I'll update the comments to clarify this, and reference a partial parser.

**Comment by str4d** [comment]
Addressed @gtank's comments.
